function Banner() {
  return (
    <div className="flex flex-col lg:flex-row lg:space-x-5 justify-between font-bold px-10 py-5 mb-10">
      <div>
        <h1 className="md:text-5xl lg:text-7xl text-4xl">
          Artificial Intelligence Blog
        </h1>

        <span className="font-gray font-light">
          This website is a hub for all things AI-written blogs, providing
          readers with access to a vast collection of articles generated by
          advanced machine learning algorithms. From technology and science to
          entertainment and lifestyle, the site covers a wide range of topics.
          Whether you are an AI enthusiast, a curious reader, or just looking
          for unique perspectives on various subjects, this website has
          something for everyone.
        </span>
      </div>
    </div>
  );
}

export default Banner;
