import Banner from "../../components/Banner";
import Header from "../../components/Header";
import "../../styles/globals.css";

export const metadata = {
  title: "AI Blog",
  description:
    "This website is a hub for all things AI-written blogs, providing readers with access to a vast collection of articles generated by advanced machine learning algorithms. From technology and science to entertainment and lifestyle, the site covers a wide range of topics. Whether you are an AI enthusiast, a curious reader, or just looking for unique perspectives on various subjects, this website has something for everyone.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-7xl mx-auto">
        <Header />
        {children}
      </body>
    </html>
  );
}
